### ISSUE TITLE
undefined mehtod 'delegate'

### ISSUE THREAD

**Issue by faridanoosheh** [petalmd/rubocop-petal#76]
After recent modif, not possible to run rubocop  bcz of this error:

![Screenshot 2024-01-22 at 10 00 01 AM](https://github.com/petalmd/rubocop-petal/assets/67595132/e2143339-cebc-4d3f-9215-4d4456fb7f2a)

<details><summary>Details</summary>

```bash
master!petalmd.rails * $> rubocop 
undefined method `delegate' for RuboCop::Cop::RSpec::AggregateExamples::Language::SelectorSet:Class
Did you mean?  DelegateClass
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:27:in `<class:SelectorSet>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:14:in `<module:Language>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:10:in `<class:AggregateExamples>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:9:in `<module:RSpec>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:7:in `<module:Cop>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:6:in `<module:RuboCop>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/language.rb:5:in `<top (required)>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/matchers_with_side_effects.rb:3:in `require_relative'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples/matchers_with_side_effects.rb:3:in `<top (required)>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples.rb:3:in `require_relative'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rubocop-petal-1.3.0/lib/rubocop/cop/rspec/aggregate_examples.rb:3:in `<top (required)>'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
/Users/fanooshehpour/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'

```

</details>

**Comment by ericproulx** [comment]
Why is it not failing on CI ?

**Comment by faridanoosheh** [comment]
seems to be a matter of different versions
cause it works with `bundle exec rubocop`

**Comment by Bhacaz** [comment]
@faridanoosheh maybe try `bundle exec rubocop`? without the `bundle exec` I'm not sure what version of rubocop (or any dependencies) you're using
